### PR TITLE
Pages not rendering correctly over https

### LINKED ISSUE #14: Pages not rendering correctly over HTTPS due to Mixed Content error
# Problem Statement
When loading hydra-cg.com over [http](http://www.hydra-cg.com) the webpage works but it fails when loaded with [https](https://www.hydra-cg.com).

## Cause
This is because the yui.yahooapis.com and fonts.googleapis.com styles and fonts, respectively, are loaded over `http` on lines 11 through 17 of `index.html`.

The google fonts are available over `https`, but unfortunately the yui components are not.

# Proposal
1. Update `index.html` to use `https://fonts.googleapis.com/css?family=Exo:400,700%22`
2. Vendor the yui stylesheets and serve them from hydra-cg.com

### PR DESCRIPTION
**Pull request by MageMasher**
This *May* close #14 , I can't be certain since I can't confirm it myself locally.

### CODE REVIEW

**Comment by tpluscode** [comment]
Thank you @MageMasher. Sorry, we missed your PR

**Comment by inf3rno** [comment]
I am not sure Markus is still watching this repo. I had the impression when he wrote on the mailing list that he left the project to Karol. (2018. dec. 16)

> Hi folks,
> 
> I should have done this quite a while ago, but with the recent discussions
> about Hydra's state it's finally time to make room for new leadership in
> this community. I'm stepping down from any leadership role, real or
> perceived, I have in this group. It's been a very long time since I've had
> enough spare cycles to meaningfully lead the development and I apologize for
> not having done this sooner.
> 
> I had a chat with Karol recently and given that he's interested in pushing
> Hydra further, I decided to make him a chair of this W3C community group.
> I'll probably not be able to resist the temptation to lurk around and
> observe in which direction you are going to drive Hydra - I'll refrain from
> stepping in though. That also means, that you should never ever wait or
> block any decision on me. It is in your hands now.
> 
> I hope that not only Karol, but also a few others in this community will
> step forward and take up the great work that this community has done over
> the past several years.
> 
> 
> All the best,
> Markus

**Comment by alien-mcl** [comment]
@inf3rno, indeed Markus stepped down and let me take it over. Sorry for missing this PR - I was focused on Heracles.net and Heracles.ts recently.

Other thing is that I didn't experience issues with HTTPS for Hydra-CG's site - it seems OK. Looks like Markus did change something on the site without toucing the repo (last modification date is from 12 Dec 2018 19:36:04 GMT - just before my watch)

**Comment by alien-mcl** [comment]
I've applied some suggestions to reflect what's actually on site.

**Comment by inf3rno** [comment]
@alien-mcl Wouldn't it be better to take away the reviewer title from him? I mean people can still request a review from him even if he is not here, which can lead to confusion.

> MageMasher requested a review from lanthaler 21 days ago

**Comment by MageMasher** [comment]
Hi @alien-mcl , @tpluscode , @inf3rno In case there is concern about what the issue actually *looks* like here is a comparison on latest firefox.

#HTTP 
Screen Shot 2020-03-14 at 11 57 50 PM

#HTTPS 
Screen Shot 2020-03-14 at 11 58 40 PM

**Comment by tpluscode** [comment]
Can you actually do that? Markus is the repo owner and I think he will always be a potential reviewer

**Comment by alien-mcl** [comment]
Damn GH - didn't submit my review :/

**Comment by MageMasher** [comment]
@alien-mcl If I change the href's to use the new `https` suggestions and I remove the vendored css will that be sufficient to move this forward?

**Comment by alien-mcl** [comment]
I've comitted suggestions. Merging

**Pull request merged**
